#!/usr/bin/env ruby

require "salary_summary"
include SalarySummary

Persistence::UnitOfWork.new_current
@repository    = Repositories::SalariesRepository.new
@table_builder = Builders::TableBuilder.new(@repository)
@information   = ''

COMMANDS = {
  salary: "enter salary\n",
  table: "print table\n",
  export: "export to file\n",
  find: "find\n",
  help: "help\n",
  exit: "exit\n"
}

puts 'Hello !! Welcome to the Salary Summary !'
puts 'We save all your salary records into collections and make comparisons at your disposal.'
puts "Commands are:"
print COMMANDS.map { |_, value| value.tr("\n", '')  }.join(' - ')
print "\n"
puts 'Type Ctrl-C to exit.'
print "\n"

loop do
  print 'What do you want to do ? '
  command = gets
  puts 'Command not found...' unless COMMANDS.values.include? command

  case command
  when COMMANDS.dig(:salary)
    print 'Which period (format: month_name/YYYY) ? '
    @information << "#{gets.tr("\n", '')}: "

    if @information !~ /[a-zA-Z\:?]/
      puts 'You have to enter a period first...'
      redo
    end

    print 'Which value ? '

    @information << gets
    salary = Interpreters::InformationInterpreter.new.parse(@information)

    if salary
      @repository.insert(salary)
      puts "Saved correctly into the database: period: #{salary.month}/#{salary.year}, amount: #{salary.amount}"
    else
      puts "We found an error to save that salary, buddy. Please, try again."
      @information = ''
      redo
    end

    @information = ''
  when COMMANDS.dig(:table)
    print "\n"
    @table_builder.build_entries
    print "\n"
    @table_builder.build_sum_footer
  when COMMANDS.dig(:export)
    if @repository.sum_by_amount.zero? and @repository.find_all.none?
      puts 'Enter your salary values first...'
      redo
    end

    print 'Enter the report file name: '
    file_name = gets.gsub(/\s*/, '')

    Exporters::AnnualSalaryReport.new(@repository).export(file_name)

    puts 'Report file saved successfully !'
  when COMMANDS.dig(:exit)
    puts 'Good-bye for now !!'
    exit
  end

  print "\n"
end
