#!/usr/bin/env ruby

require "salary_summary"
include SalarySummary

@repository    = Exporters::SalariesRepository
@table_builder = Builders::TableBuilder.new(@repository)
@information   = ''

COMMANDS = {
  salary: "enter salary\n",
  table: "print table\n",
  export: "export to file\n",
  find: "find\n",
  help: "help\n",
  exit: "exit\n"
}

puts 'Hello !! Welcome to the Salary Summary !'
puts 'We save all your salary records into collections and make comparisons at your disposal.'
puts "Commands are:"
print COMMANDS.map { |_, value| value.tr("\n", '')  }.join(' - ')
print "\n"
puts 'Type Ctrl-C to exit.'
print "\n"

loop do
  print 'What do you want to do ? '
  command = gets
  puts 'Command not found...' unless COMMANDS.values.include? command

  case command
  when COMMANDS.dig(:salary)
    print 'Which period ? '
    @information << "#{gets.tr("\n", '')}: "

    if @information !~ /[a-zA-Z\:?]/
      puts 'You have to enter a period first...'
      redo
    end

    print 'Which value ? '

    @information << gets
    salary = Interpreters::InformationInterpreter.parse!(@information)

    print 'Please, type the name of the collection to save it: '

    collection_name = gets.gsub(/\s*/, '')

    @repository.save!(salary, collection_name)

    puts "Saved correctly into the database: period: #{salary.period}, amount: #{salary.amount}"

    @information = ''
  when COMMANDS.dig(:table)
    print 'Enter the name of the collection: '
    collection_name = gets.gsub(/\s*/, '')

    print "\n"
    puts "---Period------Amount---"
    @table_builder.build_entries_on collection_name
    print "\n"
    @table_builder.build_sum_footer_for collection_name
  when COMMANDS.dig(:export)
    print 'Enter the name of the collection: '
    collection_name = gets.gsub(/\s*/, '')

    if @repository.sum(collection_name).zero? and @repository.find_on(collection_name).none?
      puts 'Enter your salary values first...'
      redo
    end

    print 'Enter the report file name: '
    file_name = gets.gsub(/\s*/, '')

    Exporters::AnnualSalaryReport.new(@repository).save(collection_name, file_name)

    puts 'Report file saved successfully !'
  when COMMANDS.dig(:exit)
    puts 'Good-bye for now !!'
    exit
  end

  print "\n"
end
